<?php

namespace App;
use Illuminate\Support\Facades\Auth;
use Illuminate\Database\Eloquent\Model;

class Attachment extends Model
{
    protected $table = 'attachment';

    protected $fillable = [
        'attachmentid',
        'attachmentname',
        'createdby',
        'attachmenttype',
        'ofd6cid',
        'ofd6id',
        'ofd6bid',
        'ofd6aid',
    ];

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::saving(function($table)  {
            $table->createdby = Auth::user()->id;
        });
    }

    public function injury(){
        return $this->belongsTo(\App\Injury::class);
    }

    public function accident(){
        return $this->belongsTo(\App\Accident::class);
    }
    public function biological(){
        return $this->belongsTo(\App\Biological::class);
    }
    public function hazmat(){
        return $this->belongsTo(\App\hazmat::class);
    }

}
