<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;

class Injury extends Model
{
    protected $primaryKey = 'ofd6ID';

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::saving(function($table)  {
            $table->User_Login_ID = Auth::user()->id;
        });
    }
    protected $fillable = [

        'reportNum',
        'createDate',
        'injuryDate',
        'injuredEmployeeName',
        'injuredEmployeeID',
        'assignmentInjury',
        'shift',
        'frmsIncidentNum',
        'callFSupSwdBC',
        'User_Login_ID',
        'policeOfficerCompleteSign',
        'callFireSupervisor',
        'createdby',
        'updatedby',
        'corVelID',
        'captainID',
        'battalionChiefID',
        'acOnDutyID',
        'status1',
    ];


    public function attachment(){
        return $this->hasMany(\App\Attachment::class);
    }
}
